### ISSUE TITLE
Conflict script visual editor

### ISSUE THREAD

**Issue by bugsmafia** [getk2/k2-v3-dev-build#260] opened 2015-09-28 05:21 UTC
Installed clean version Joomla Joomla! 3.4.5
next installed K3 v3.
Default editor - CodeMirror

The editor is not loaded into the K3
Click the Save button

JavaScript error -Uncaught TypeError: Cannot read property 'getValue' of undefined
---
...
var K2Editor = {init : function () {}, setContent : function (name, content) {Joomla.editors.instances[name].setValue(content);}, getContent : function (name) {Joomla.editors.instances[name].getValue();}, save : function (name) {document.getElementById(name).value = Joomla.editors.instances[name].getValue();}};
...
---

**Comment by kavadas** [comment] 2015-09-28 13:41
Duplicate of #52

**Closed** 2016-02-27 14:11 UTC
Labels: duplicate
