### ISSUE TITLE
When is frontend editing going to be finalized?

### ISSUE THREAD

**Issue by Mr-Anonymous** [getk2/k2-v3-dev-build#107] opened 2014-10-21 07:53 UTC
@kavadas when would you be finalizing the frontend editing bits?

**Comment by paulvanharen** [comment] 2016-01-26 18:10
@kavadas 
This is an information request and not a bug. Therefore I propose to close this here and optionally to open a corresponding one in the JoomlaWorks forum.

**Closed** 2016-02-29 12:45 UTC
