### ISSUE TITLE
Backend Publish Date 

### ISSUE THREAD

**Issue by Twincarb** [getk2/k2-v3-dev-build#265] opened 2015-10-03 14:28 UTC
Not so much a bug as an enhancement probably needed.

If the date is manually deleted from the publish date and then an article is then saved, I would expect it to take the Created Date and time. Instead it is given
-0001-11-30 and a blank time gives 00:00

The Time picker possibly needs a rethink as the list of times isn't practical in real world situations

There are also 2 extra Start time & End Time options which have no description or identifiable use

**Comment by paulvanharen** [comment] 2015-12-03 19:48
Hi Twincarb,

I've tried to reproduce these issues. I was able to reproduce items 2 (time picker) and saw the unused Start time & End time. However, I could not reproduce your first issue. 

Are you still able to reproduce this issue?

Thanks and regards, Paul

**Comment by Twincarb** [comment] 2015-12-03 20:14
@paulvanharen can you just confirm which issue was the first one your referring to? It maybe that was the one that's related to an issue on the Joomla build I was working on.

**Comment by paulvanharen** [comment] 2015-12-04 08:49
@Twincarb in your original issue (#265 in k2-v3-dev-build) you mention three issues, all related to the publishing dates in the back-end: 
1) a useless date/time after clearing the date/time information
2) the time picker that produces a list with 288 entries, each 5 minutes apart
3) four fields (Start date/time, End date/time) that have no purpose.

I understand the issues 2) and 3), but I was not able to reproduce issue 1). It may have been fixed in the mean time, or I don't understand the full details how to reproduce it.

Therefore I would like to ask to quickly update to the latest k2-v3-dev-build and check whether the issue persists.

Thanks and regards, Paul

**Comment by Twincarb** [comment] 2015-12-04 17:58
The way to test the first one is to create a new k2 article, and save it.
Then go to publishing click on the date the date window opens just click delete, do the same for time so the box's are left empty. 
Re-Save the document
Go back to the publishing details and the date/time will show as:
-0001-11-30 and a blank time gives 00:00

I have just created a fresh Joomla install and tested it, the above doesn't happen now. it would be helpful if a couple of people can confirm this doesn't happen now.

Dave

**Closed** 2016-03-07 11:44 UTC
Labels: enhancement
