### ISSUE TITLE
Add a loading icon/screen when we click

### ISSUE THREAD

**Issue by austenn01** [getk2/k2-v3-dev-build#139] opened 2014-12-14 13:47 UTC
I just wanted to post a feature request...This has kinda been a frustration when using the new K2.

When in the backend K2 component,.....you will click the button to 'add a new K2 item' for example...

With other extensions, there is something in the web browser that twirls or moves to tell us the user that the request is processing and that something is happening.

When clicking on things in K2, there is nothing to show the user that they have actually clicked a button (until the page loads to a new screen). I myself and I have seen many others test the new K2, and they click for example the add new k2 item button multiple times, as it doesn't look like anything is happening..

So the suggestion, is to have a loading icon (like when we install an extension via the Joomla extension manager...we get the Joomla icon that moves and changes, thus we know that something is happening.

I know this seems like a very small request, but I can tell you from watching 100's of clients navigate websites, that they expect things to happen immediately, and if they don't see anything happening, they just keep clicking the same button over and over again.

Thanks,

P.S.

I have attached a screen shot of the Joomla installation
![joomla-instalation-action-icon](https://cloud.githubusercontent.com/assets/3283909/5427508/ae63c376-83ef-11e4-91c2-92a480cdb501.jpg)
 action icon

**Comment by paulvanharen** [comment] 2016-01-25 18:07
@kavadas 
I guess this is a duplicate of #86.

**Closed** 2016-02-27 11:56 UTC
Labels: enhancement
