### ISSUE TITLE
Attachments behaving erratically

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2-v3-dev-build#268] opened 2015-10-08 04:55 UTC
I know that's super unclear, but I cannot for the life of me figure out what's going on here.

If I create a single attachment to an item, it will download OK the first few times. But after X number of downloads, I'll suddenly start getting 404s.

Delete and replace the attachment and it'll work for a while, but after a while 404s.

**Comment by kbrookes** [comment] 2015-10-10 04:49
Quick update on this one - this has gotten so bad I've had to switch to using extra fields.

Still hard to get a handle on exactly what was happening, but it seemed to be that when one failed (and the others were fine) that removing and re-attaching the file would make it work for that one, but one or more of the others would immediately start failing.

**Comment by kavadas** [comment] 2015-10-12 08:36
Can you check if the file is still on your server when you start getting 404 errors? Here is the code that makes the download: https://github.com/joomlaworks/k2-v3-dev-build/blob/master/components/com_k2/views/attachments/view.html.php . 

As you can see you will get a 404 if the link is incorrect or the file is missing.

**Comment by kbrookes** [comment] 2015-10-12 22:45
Files are definitely still on the server - I've switched to using extraFields now, but pulling the same file from the server. The extraFields versions work, the attachments versions stop working after X amount of time and never work again.

**Comment by kavadas** [comment] 2015-10-13 08:40
So you are using the same files in extra fields? I am talking about the files under media/k2/attachments. Is there any chance that you changed either the attachments root folder or the filesystem driver in K2 settings page?

**Comment by kbrookes** [comment] 2015-10-15 21:42
No.

I was using the actual attachments system, uploading files directly (not browsing from the server) where they were served from media/k2/attachments.

I've been forced to switch to using ExtraFields to serve these files due to the attachments failing.

I have not changed the root folder or filesystem driver.

The occurrences followed a specific pattern:

Upload a single attachment to each item in a category. Immediately post upload, all files would work. By the time I finished uploading files to the items, the first item's attachments would be failing. If I fixed those, other item's attachments would start failing.

Because this site is going live today, I've stopped using attachments and have switched to extraFields out of necessity.

**Comment by kavadas** [comment] 2015-10-16 08:45
We will look into it again. Thanks for reporting. However, since you mentioned that the site is going live i would like to remind you that this extension is still under development and should not be used in production sites.

**Comment by kbrookes** [comment] 2015-10-16 08:52
Well aware, I took a gamble on it being released by now when we started the project two months ago.

I lost, but there was functionality in there that was a lot easier to achieve with v3. And it's been very thoroughly tested.

Slightly high profile project too, can't discuss openly but would be a good tentpole site for k2v3.

Happy to discuss privately if you're interested.

kelsey@lovedlockedloaded.com

**Comment by paulvanharen** [comment] 2015-12-06 12:46
@kbrookes 
I've tried to reproduce the reported issue. On a blank Joomla site with latest k2 v3 dev build, I've created just one article with an image as attachment. I was able to download the attachment 30 times without any issues. 

Are you still able to reproduce this issue?

Thanks and regards, Paul

**Comment by kbrookes** [comment] 2015-12-06 22:13
Hi Paul,

It wasn't a problem when I first started the build, but once I had a few
articles with attachments in there it was a constant plague. It seemed to
be bound up with uploading an attachment to one article would cause another
to lose its link to its own.

Because this was for a live site (yes, I know, I was under the impression
that v3 would be finalised much sooner than it has been) I switched to
extra fields instead.

I haven't had time to do more testing since.

K

**Comment by fevangelou** [comment] 2016-03-08 09:32
@kbrookes As we are (finally) nearing the final rollout of K2 v3, I'd like to comment that this is probably server related. What we should have asked you to do is grab a copy of the site and test it locally or on a different server (either newly setup or surely not the same identical setup as the one you currently have the site on).

Only a server configuration or firewall could cause such a behaviour. PHP usually either works or it doesn't.

Closing the issue for now. If anyone else has something to add, we'll re-open it. For the time being, the issue cannot be reproduced on our side.

**Closed by fevangelou** 2016-03-08 09:32 UTC
