### ISSUE TITLE
[Feature Request]: Assign Extra Fields to Multiple Extra Field Groups

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#108] opened 2014-10-24 14:30 UTC
Offer users the ability to assign an extra field to multiple extra field groups (multi-select)

For example, if I create a Short URL extra field to store the Bitly link for each item. That extra field is relevant across all categories, allowing the user to use that extra field for each category by offering the ability to assign it to each extra field group would have it so that the site administrator does not have to create a "Bitly Link" extra field for each category (bitly_blog, bitly_about, bitly_shop, etc.)

**Comment by paulvanharen** [comment] 2016-03-07 09:40
@heyjoecampbell 
If we were to implement an extra field group as an extra field, one can create trees of extra fields. 
That would provide an alternative path to realize what you're looking for, am I right? See also #30.

**Comment by heyjoecampbell** [comment] 2016-03-07 12:41
I do not understand - please clarify

**Comment by paulvanharen** [comment] 2016-03-07 12:56
I understand your initial request as follows:
*) you have an extra field (set), that you want to see in multiple groups
*) the multiple groups are variants from each other 

If you would be able to put the fields common to categories in one group, and then add this group as a whole to a category specific group, would you then have the flexibility you're looking for?

**Comment by heyjoecampbell** [comment] 2016-03-07 17:33
Use Case:

I use extra fields to render my main item image (image_item), because it give me full control over the image (file name, etc.)

Each item in each category uses/requires a main item image. Which would currently require a unique extra field for each category:

image_item_about
image_item_blog
image_item_directory

My request is that an extra field (in this use case the **image_item** extra field) be accessible by each extra field group. The idea is going from a limited rendering of blocks (groups) of extra fields to more flexible individual extra field rendering architecture which would enable a site to render different extra field content throughout various locations of page (meta head, title, image, sidebar, etc.)

**Comment by paulvanharen** [comment] 2016-03-24 19:53
Hi Joe,
I'm still trying to understand what the problem is. 

You have different categories (about, blog and directory), and each of these categories have a mixture of extra field groups assigned. E.g. you can create an extra field group for your image and assign that group to all of your categories. 

But I guess this is not what you're trying to accomplish. 

Regards, Paul

**Comment by heyjoecampbell** [comment] 2016-03-29 21:44
If one could create a for lack of better words "General" extra field group, then it could be used for each and every category (About Us, Blog, Directory). 

This works if multiple Extra Field Groups are offered. So that each category could look like this:

About Us
- extra field group: General
- extra field group: About

Blog
- extra field group: General
- extra field group: Blog
- extra field group: Special Links

Directory
- extra field group: General
- extra field group: Directory
- extra field group: Extras


Does this make sense? The ability to apply multiple Extra Field Groups would be needed for this to work. This feature will be available in v3, correct?

Until then, I have all my extra fields (for each respective category) housed one "General" extra field group. I then have that one extra field group applied to every category :)

**Comment by paulvanharen** [comment] 2016-04-01 06:57
Adding the multiple extra field groups to a category and adding the same extra field group to multiple categories is already implemented. Does this address your needs? If so, I'll close this issue.

**Comment by heyjoecampbell** [comment] 2016-04-01 07:20
Multiple extra field groups is a feature that will be included in v3, correct?

**Closed** 2016-04-29 16:58 UTC
Labels: enhancement
