### ISSUE TITLE
Unable to edit items or add content to new items - Errors in Edit Item after data import

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2-v3-dev-build#233] opened 2015-07-20 20:55 UTC
I am unable to edit items or add content to new items after data import from 2.6.9. Errors in Edit Item after data import:

 Warning[2] Illegal string offset 'id'. Line 67 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Warning[2] Illegal string offset 'id'. Line 67 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Warning[2] Invalid argument supplied for foreach(). Line 46 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: start_date. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: end_date. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: created_by. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _attachments. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _tags. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _media. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _galleries. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 98 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php
 Warning[2] Illegal string offset 'id'. Line 74 in file /home1/engetsui/public_html/administrator/components/com_k2/resources/resource.php

**Comment by kavadas** [comment] 2015-07-21 09:22
What do you mean data import? Have you upgraded from K2v2 to K2v3?

**Comment by Simon-Davies** [comment] 2015-07-21 23:05
Sorry I was tired when I wrote the first message. I meant after data migration. I have updated from K2 2.6.9 to K2 3

**Comment by Simon-Davies** [comment] 2015-07-21 23:06
Sorry I was tired when I wrote the first message. I meant after data migration. I have updated from K2 2.6.9 to K2 3

**Comment by Simon-Davies** [comment] 2015-07-21 23:06
Sorry I was tired when I wrote the first message. I meant after data migration. I have updated from K2 2.6.9 to K2 3

**Comment by Simon-Davies** [comment] 2015-07-21 23:08
Sorry I was tired when I wrote the first message. I meant after data migration. I have updated from K2 2.6.9 to K2 3

**Comment by kavadas** [comment] 2015-07-22 09:44
Is K2ve installed correctly? Do you see the new user interface in the administration? Also try to open the settings page and click save.

**Comment by Simon-Davies** [comment] 2015-07-22 10:56
K2 3 is installed correctly. I see the new interface in the administration and I changed a few settings and they saved successfully. I enabled comments for public users and the change saved successfully and could be seen on the front-end. I get all those error when trying to modify the content of migrated items or create a new item. I can't modify or create any new content when I click save it doesn't save.

**Comment by kavadas** [comment] 2015-07-22 11:14
Do you have any third-party K2 or content plugins installed? Try to disable them one by one.

**Comment by Simon-Davies** [comment] 2015-07-22 12:36
I don't have any third-party K2 or content plugins installed.

**Comment by paulvanharen** [comment] 2016-02-27 11:53
I could not reproduce this issue. My take on it that it was fixed by the code update in August / September 2015.

**Closed by paulvanharen** 2016-02-27 11:53 UTC
